name: quran_app
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^1.0.0
  google_fonts: ^6.2.1
  qibla_direction: ^1.0.1
  permission_handler: ^11.3.1
  geolocator: ^12.0.0
  intl: ^0.19.0
  hijri: ^3.0.0
  geocoding: ^3.0.0
  adhan: ^2.0.0+1
  asmaulhusna: ^0.0.3
  audioplayers: ^6.0.0
  http: ^1.2.2
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0
  shared_preferences: ^2.3.1
  quran: ^1.3.0
  just_audio: ^0.9.39
  flutter_compass: ^0.8.0
  provider: ^6.1.2
  flutter_map: ^7.0.2
  osm_nominatim: ^3.0.1
  latlong2: ^0.9.1
  home_widget: ^0.6.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.12
  intl_utils: ^2.8.7
  flutter_test:
    sdk: flutter

dependency_overrides:
  flutter_compass:
    git: https://github.com/PikPakPik/flutter_compass.git

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/audio/
    - assets/json/
