import 'dart:convert';
import 'package:http/http.dart' as http;
import '../Models/hadith_model.dart'; 

class ApiService {
  final String apiKey = r'$2y$10$kLid3Tc9Clg8YZIkbVhT2eto1QApgzTeDwmzxEYp6xzvOyVKyhb2';
  final String baseUrl;

  ApiService({this.baseUrl = 'https://www.hadithapi.com/api/hadiths/'});

  Future<List<Data>> fetchHadiths() async {
    final url = Uri.parse('$baseUrl?apiKey=$apiKey');

    try {
      final response = await http.get(url);

      if (response.statusCode == 200) {
        final Map<String, dynamic> jsonResponse = json.decode(response.body);
        final Autogenerated autogenerated = Autogenerated.fromJson(jsonResponse);

        if (autogenerated.status == 200) {
          final List<Data>? data = autogenerated.hadiths?.data;
          return data ?? [];
        } else {
          throw Exception(autogenerated.message);
        }
      } else {
        throw Exception('Failed to load Hadiths');
      }
    } catch (e) {
      print('Error loading Hadiths: $e');
      return [];
    }
  }
}
