class Autogenerated {
  final int? status;
  final String? message;
  final Hadiths? hadiths;

  Autogenerated({this.status, this.message, this.hadiths});

  factory Autogenerated.fromJson(Map<String, dynamic> json) {
    return Autogenerated(
      status: json['status'] as int?,
      message: json['message'] as String?,
      hadiths: json['hadiths'] != null ? Hadiths.fromJson(json['hadiths']) : null,
    );
  }
}
class Hadiths {
  final int? currentPage;
  final List<Data>? data;
  final String? firstPageUrl;
  final int? from;
  final int? lastPage;
  final String? lastPageUrl;
  final List<Links>? links;
  final String? nextPageUrl;
  final String? path;
  final int? perPage;
  final String? prevPageUrl;
  final int? to;
  final int? total;

  Hadiths({
    this.currentPage,
    this.data,
    this.firstPageUrl,
    this.from,
    this.lastPage,
    this.lastPageUrl,
    this.links,
    this.nextPageUrl,
    this.path,
    this.perPage,
    this.prevPageUrl,
    this.to,
    this.total,
  });

  factory Hadiths.fromJson(Map<String, dynamic> json) {
    return Hadiths(
      currentPage: json['current_page'] as int?,
      data: (json['data'] as List<dynamic>?)
          ?.map((item) => Data.fromJson(item as Map<String, dynamic>))
          .toList(),
      firstPageUrl: json['first_page_url'] as String?,
      from: json['from'] as int?,
      lastPage: json['last_page'] as int?,
      lastPageUrl: json['last_page_url'] as String?,
      links: (json['links'] as List<dynamic>?)
          ?.map((item) => Links.fromJson(item as Map<String, dynamic>))
          .toList(),
      nextPageUrl: json['next_page_url'] as String?,
      path: json['path'] as String?,
      perPage: json['per_page'] as int?,
      prevPageUrl: json['prev_page_url'] as String?,
      to: json['to'] as int?,
      total: json['total'] as int?,
    );
  }
}
class Data {
  final int? id;
  final String? hadithNumber;
  final String? englishNarrator;
  final String? hadithEnglish;
  final String? hadithUrdu;
  final String? urduNarrator;
  final String? hadithArabic;
  final String? headingArabic;
  final String? headingUrdu;
  final String? headingEnglish;
  final String? chapterId;
  final String? bookSlug;
  final String? volume;
  final String? status;
  final Book? book;
  final Chapter? chapter;

  Data({
    this.id,
    this.hadithNumber,
    this.englishNarrator,
    this.hadithEnglish,
    this.hadithUrdu,
    this.urduNarrator,
    this.hadithArabic,
    this.headingArabic,
    this.headingUrdu,
    this.headingEnglish,
    this.chapterId,
    this.bookSlug,
    this.volume,
    this.status,
    this.book,
    this.chapter,
  });

  factory Data.fromJson(Map<String, dynamic> json) {
    return Data(
      id: json['id'] as int?,
      hadithNumber: json['hadithNumber'] as String?,
      englishNarrator: json['englishNarrator'] as String?,
      hadithEnglish: json['hadithEnglish'] as String?,
      hadithUrdu: json['hadithUrdu'] as String?,
      urduNarrator: json['urduNarrator'] as String?,
      hadithArabic: json['hadithArabic'] as String?,
      headingArabic: json['headingArabic'] as String?,
      headingUrdu: json['headingUrdu'] as String?,
      headingEnglish: json['headingEnglish'] as String?,
      chapterId: json['chapterId'] as String?,
      bookSlug: json['bookSlug'] as String?,
      volume: json['volume'] as String?,
      status: json['status'] as String?,
      book: json['book'] != null ? Book.fromJson(json['book']) : null,
      chapter: json['chapter'] != null ? Chapter.fromJson(json['chapter']) : null,
    );
  }
}
class Book {
  final int? id;
  final String? bookName;
  final String? writerName;
  final String? aboutWriter;
  final String? writerDeath;
  final String? bookSlug;

  Book({
    this.id,
    this.bookName,
    this.writerName,
    this.aboutWriter,
    this.writerDeath,
    this.bookSlug,
  });

  factory Book.fromJson(Map<String, dynamic> json) {
    return Book(
      id: json['id'] as int?,
      bookName: json['bookName'] as String?,
      writerName: json['writerName'] as String?,
      aboutWriter: json['aboutWriter'] as String?,
      writerDeath: json['writerDeath'] as String?,
      bookSlug: json['bookSlug'] as String?,
    );
  }
}
class Chapter {
  final int? id;
  final String? chapterNumber;
  final String? chapterEnglish;
  final String? chapterUrdu;
  final String? chapterArabic;
  final String? bookSlug;

  Chapter({
    this.id,
    this.chapterNumber,
    this.chapterEnglish,
    this.chapterUrdu,
    this.chapterArabic,
    this.bookSlug,
  });

  factory Chapter.fromJson(Map<String, dynamic> json) {
    return Chapter(
      id: json['id'] as int?,
      chapterNumber: json['chapterNumber'] as String?,
      chapterEnglish: json['chapterEnglish'] as String?,
      chapterUrdu: json['chapterUrdu'] as String?,
      chapterArabic: json['chapterArabic'] as String?,
      bookSlug: json['bookSlug'] as String?,
    );
  }
}
class Links {
  final String? url;
  final String? label;
  final bool? active;

  Links({
    this.url,
    this.label,
    this.active,
  });

  factory Links.fromJson(Map<String, dynamic> json) {
    return Links(
      url: json['url'] as String?,
      label: json['label'] as String?,
      active: json['active'] as bool?,
    );
  }
}

